using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace SMADX.Services
{
    /// <summary>
    /// Génère un script PowerShell qui interroge un domaine AD réel
    /// et produit un fichier JSON importable dans Active Directory Simulator.
    /// </summary>
    public class ADImportPowerShellService
    {
        public async Task<bool> GenerateImportScriptAsync(string filePath)
        {
            try
            {
                var script = BuildScript();
                await File.WriteAllTextAsync(filePath, script, new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Erreur génération script import : {ex.Message}");
                return false;
            }
        }

        private static string BuildScript()
        {
            var s = new StringBuilder();
            L(s, "<#");
            L(s, ".SYNOPSIS");
            L(s, "    Export Active Directory to a JSON file importable into Active Directory Simulator.");
            L(s, "");
            L(s, ".DESCRIPTION");
            L(s, "    This script reads the structure of an Active Directory domain (OUs, Containers, Users,");
            L(s, "    Groups, Computers, GMSAs, GPOs, PSOs) and produces a JSON file in the format expected");
            L(s, "    by Active Directory Simulator. Output file uses the .smad-x.json extension.");
            L(s, "");
            L(s, ".PARAMETER OutputPath");
            L(s, "    Path of the output file. Default: .\\AD_Export.smadx.json");
            L(s, "");
            L(s, ".PARAMETER DomainDN");
            L(s, "    DN of the target domain. Default: current domain detected automatically.");
            L(s, "");
            L(s, ".EXAMPLE");
            L(s, "    .\\Export-ADToSMAD-X.ps1");
            L(s, "");
            L(s, ".NOTES");
            L(s, "    Requires : ActiveDirectory PowerShell module (RSAT)");
            L(s, "    Rights   : Domain Read");
            L(s, "#>");
            L(s, "");
            L(s, "param(");
            L(s, "    [string]$OutputPath = '',");
            L(s, "    [string]$DomainDN   = ''");
            L(s, ")");
            L(s, "");
            L(s, "Set-StrictMode -Version 2.0");
            L(s, "$ErrorActionPreference = 'Stop'");
            L(s, "");
            L(s, "# ── 1. Prerequisites ─────────────────────────────────────────────────────────────");
            L(s, "if (-not (Get-Module -ListAvailable -Name ActiveDirectory)) {");
            L(s, "    Write-Error 'The ActiveDirectory module (RSAT) is required.'");
            L(s, "    exit 1");
            L(s, "}");
            L(s, "Import-Module ActiveDirectory -ErrorAction Stop");
            L(s, "");
            L(s, "# ── 2. Target domain ─────────────────────────────────────────────────────────");
            L(s, "if ([string]::IsNullOrWhiteSpace($DomainDN)) {");
            L(s, "    $domain     = Get-ADDomain");
            L(s, "    $DomainDN   = $domain.DistinguishedName");
            L(s, "    $domainName = $domain.DNSRoot");
            L(s, "} else {");
            L(s, "    $domainName = ($DomainDN -replace 'DC=','' -replace ',DC=','.').Trim(',').Trim()");
            L(s, "}");
            L(s, "Write-Host \"Domaine cible : $domainName ($DomainDN)\" -ForegroundColor Cyan");
            L(s, "");
            L(s, "# ── OutputPath : domaine + date si non fourni ────────────────────────────────");
            L(s, "if ([string]::IsNullOrWhiteSpace($OutputPath)) {");
            L(s, "    $dateStamp  = Get-Date -Format 'yyyyMMdd_HHmmss'");
            L(s, "    $safeDomain = $domainName -replace '[^a-zA-Z0-9._-]','_'");
            L(s, "    $OutputPath = \".\\${safeDomain}_${dateStamp}.smad-x.json\"");
            L(s, "}");
            L(s, "");
            L(s, "# ── 3. Helpers ───────────────────────────────────────────────────────────────");
            L(s, "function ConvertTo-JsonString([string]$str) {");
            L(s, "    if ($null -eq $str) { return '' }");
            L(s, "    $str = $str.Replace('\\','\\\\').Replace('\"','\\\"').Replace(\"`n\",'\\n').Replace(\"`r\",'\\r').Replace(\"`t\",'\\t')");
            L(s, "    return $str");
            L(s, "}");
            L(s, "");
            L(s, "function Format-Date($d) {");
            L(s, "    if ($null -eq $d) { return (Get-Date -Format 'o') }");
            L(s, "    try { return ([datetime]$d).ToString('o') } catch { return (Get-Date -Format 'o') }");
            L(s, "}");
            L(s, "");
            L(s, "function Get-SimType([string]$objectClass) {");
            L(s, "    switch ($objectClass) {");
            L(s, "        'organizationalUnit'                  { return 'OrganizationalUnit' }");
            L(s, "        'container'                           { return 'Container' }");
            L(s, "        'builtinDomain'                       { return 'Container' }");
            L(s, "        'user'                                { return 'User' }");
            L(s, "        'group'                               { return 'Group' }");
            L(s, "        'computer'                            { return 'Computer' }");
            L(s, "        'msDS-GroupManagedServiceAccount'     { return 'GMSA' }");
            L(s, "        'groupPolicyContainer'                { return 'Policy' }");
            L(s, "        'msDS-PasswordSettings'               { return 'PasswordSettingsObject' }");
            L(s, "        default                               { return 'Container' }");
            L(s, "    }");
            L(s, "}");
            L(s, "");
            L(s, "# ── 4. Collect GPOs ─────────────────────────────────────────────────────");
            L(s, "Write-Host 'Collecting GPOs...' -ForegroundColor Yellow");
            L(s, "$gpoMap = @{}");
            L(s, "try {");
            L(s, "    Get-ADObject -Filter { objectClass -eq 'groupPolicyContainer' } `");
            L(s, "                 -SearchBase $DomainDN `");
            L(s, "                 -Properties DisplayName,cn | ForEach-Object {");
            L(s, "        $key = $_.DistinguishedName.ToLower()");
            L(s, "        $gpoMap[$key] = if ($_.DisplayName) { $_.DisplayName } else { $_.cn }");
            L(s, "    }");
            L(s, "} catch { Write-Warning \"Failed to read GPOs : $_\" }");
            L(s, "");
            L(s, "# ── 5. GPO links ─────────────────────────────────────────────────────────────");
            L(s, "function Get-GPOLinksForDN([string]$dn) {");
            L(s, "    try {");
            L(s, "        $obj = Get-ADObject -Identity $dn -Properties gpLink");
            L(s, "        if ($obj.gpLink) {");
            L(s, "            $links = [regex]::Matches($obj.gpLink, '\\[LDAP://([^\\]]+);') | ForEach-Object { $_.Groups[1].Value }");
            L(s, "            return @($links | ForEach-Object { $k = $_.ToLower(); if ($gpoMap.ContainsKey($k)) { $gpoMap[$k] } else { $_ } })");
            L(s, "        }");
            L(s, "    } catch {}");
            L(s, "    return @()");
            L(s, "}");
            L(s, "");
            L(s, "# ── 6. PSOs ──────────────────────────────────────────────────────────────────");
            L(s, "Write-Host 'Collecting PSOs...' -ForegroundColor Yellow");
            L(s, "$psoObjects = @()");
            L(s, "try {");
            L(s, "    $psoObjects = Get-ADFineGrainedPasswordPolicy -Filter * | Select-Object `");
            L(s, "        Name,DistinguishedName,Precedence,MinPasswordLength,PasswordHistoryCount,");
            L(s, "        ComplexityEnabled,MaxPasswordAge,MinPasswordAge,LockoutThreshold,");
            L(s, "        LockoutDuration,LockoutObservationWindow,AppliesTo");
            L(s, "} catch { Write-Warning \"Failed to read PSOs : $_\" }");
            L(s, "");

            L(s, "# ── 8. Recursive tree builder ────────────────────────────────────────────────");
            L(s, "function Build-NodeJson {");
            L(s, "    param([string]$dn, [string]$name, [string]$simType, [object]$adObj, [int]$depth = 0)");
            L(s, "");
            L(s, "    $id          = [guid]::NewGuid().ToString()");
            L(s, "    $description = if ($adObj -and $adObj.Description) { ConvertTo-JsonString (($adObj.Description | Out-String).Trim()) } else { '' }");
            L(s, "");
            L(s, "    # For GPO nodes: build a rich Markdown description with DisplayName + GUID");
            L(s, "    if ($simType -eq 'Policy' -and $adObj) {");
            L(s, "        $gpoDisplay = if ($adObj.DisplayName) { $adObj.DisplayName } else { $name }");
            L(s, "        $gpoGuid    = $adObj.Name   # CN = GUID");
            L(s, "        $gpoDN      = $dn");
            L(s, "        $nl         = [char]10");
            L(s, "        $md  = '# GPO : ' + $gpoDisplay + $nl");
            L(s, "        $md += $nl");
            L(s, "        $md += '## Identifiant' + $nl");
            L(s, "        $md += '**GUID** : `' + $gpoGuid + '`' + $nl");
            L(s, "        $md += $nl");
            L(s, "        $md += '## Distinguished Name' + $nl");
            L(s, "        $md += '`' + $gpoDN + '`' + $nl");
            L(s, "        if ($adObj.Description) {");
            L(s, "            $md += $nl + '## Description' + $nl + (($adObj.Description | Out-String).Trim()) + $nl");
            L(s, "        }");
            L(s, "        $description = ConvertTo-JsonString $md");
            L(s, "    }");
            L(s, "    $created     = Format-Date $(if ($adObj) { $adObj.WhenCreated } else { $null })");
            L(s, "    $modified    = Format-Date $(if ($adObj) { $adObj.WhenChanged } else { $null })");
            L(s, "");
            L(s, "    # MemberOf");
            L(s, "    $memberOfJson = '[]'");
            L(s, "    if ($adObj -and $adObj.MemberOf) {");
            L(s, "        $names = foreach ($gdn in $adObj.MemberOf) {");
            L(s, "            try { $o = Get-ADObject -Identity $gdn -Properties SAMAccountName; $o.SAMAccountName } catch {}");
            L(s, "        }");
            L(s, "        $names = @($names | Where-Object { $_ })");
            L(s, "        if (@($names).Count -gt 0) {");
            L(s, "            $memberOfJson = '[' + (($names | ForEach-Object { '\"' + (ConvertTo-JsonString $_) + '\"' }) -join ',') + ']'");
            L(s, "        }");
            L(s, "    }");
            L(s, "");
            L(s, "    # Linked GPOs");
            L(s, "    $linkedGPOJson = '[]'");
            L(s, "    if ($simType -in @('OrganizationalUnit','Domain')) {");
            L(s, "        $links = @(Get-GPOLinksForDN $dn)");
            L(s, "        if ($links.Count -gt 0) {");
            L(s, "            $linkedGPOJson = '[' + (($links | ForEach-Object { '\"' + (ConvertTo-JsonString $_) + '\"' }) -join ',') + ']'");
            L(s, "        }");
            L(s, "    }");
            L(s, "");
            L(s, "    # Delegations (ACL) — OUs and Containers only");
            L(s, "    $delegationsJson = '[]'");
            L(s, "    if ($simType -in @('OrganizationalUnit','Container','Domain')) {");
            L(s, "        try {");
            L(s, "            $acl = Get-Acl -Path \"AD:$dn\" -ErrorAction Stop");
            L(s, "            $skipTrustees = @('NT AUTHORITY\\SYSTEM','BUILTIN\\Administrators','CREATOR OWNER',");
            L(s, "                              'NT AUTHORITY\\SELF','NT AUTHORITY\\ENTERPRISE DOMAIN CONTROLLERS',");
            L(s, "                              'Everyone','BUILTIN\\Pre-Windows 2000 Compatible Access')");
            L(s, "            $guidResetPwd   = [guid]'00299570-246d-11d0-a768-00aa006e0529'");
            L(s, "            $guidUnlockAcct = [guid]'280f369c-67c7-438e-ae98-1d46f3c6f541'");
            L(s, "            $guidComputer   = [guid]'bf967a86-0de6-11d0-a285-00aa003049e2'");
            L(s, "            $delegParts = [System.Collections.Generic.List[string]]::new()");
            L(s, "            foreach ($ace in $acl.Access) {");
            L(s, "                if ($ace -isnot [System.DirectoryServices.ActiveDirectoryAccessRule]) { continue }");
            L(s, "                $trustee = $ace.IdentityReference.Value");
            L(s, "                if ($skipTrustees -contains $trustee) { continue }");
            L(s, "                $trusteeType = 'Group'");
            L(s, "                try {");
            L(s, "                    $tObj = Get-ADObject -Filter { SAMAccountName -eq $trustee.Split('\\\\')[-1] } -Properties objectClass -ErrorAction SilentlyContinue");
            L(s, "                    if ($tObj.objectClass -eq 'user') { $trusteeType = 'User' }");
            L(s, "                    elseif ($tObj.objectClass -eq 'computer') { $trusteeType = 'Computer' }");
            L(s, "                } catch {}");
            L(s, "                $trusteeSam   = $trustee.Split('\\\\')[-1]");
            L(s, "                $ar           = $ace.ActiveDirectoryRights");
            L(s, "                $objType      = $ace.ObjectType");
            L(s, "                $right        = 'Other'");
            L(s, "                $rightCategory = 'Other'");
            L(s, "                if ($objType -eq $guidResetPwd) {");
            L(s, "                    $right = 'ResetPassword'; $rightCategory = 'PasswordReset'");
            L(s, "                } elseif ($objType -eq $guidUnlockAcct) {");
            L(s, "                    $right = 'WriteProperty:lockoutTime'; $rightCategory = 'AccountUnlock'");
            L(s, "                } elseif (($ar -band [System.DirectoryServices.ActiveDirectoryRights]::CreateChild) -and $objType -eq $guidComputer) {");
            L(s, "                    $right = 'CreateChild:computer'; $rightCategory = 'ComputerManagement'");
            L(s, "                } elseif ($ar -band ([System.DirectoryServices.ActiveDirectoryRights]::GenericAll)) {");
            L(s, "                    $right = $ar.ToString(); $rightCategory = 'FullControl'");
            L(s, "                } elseif ($ar -band [System.DirectoryServices.ActiveDirectoryRights]::WriteProperty) {");
            L(s, "                    $right = 'WriteProperty:' + $objType.ToString(); $rightCategory = 'AttributeWrite'");
            L(s, "                } else {");
            L(s, "                    $right = $ar.ToString()");
            L(s, "                }");
            L(s, "                $isInherited = ($ace.IsInherited).ToString().ToLower()");
            L(s, "                $tierVal     = ''");
            L(s, "                $delegParts.Add(\"{`\"TrusteeName`\":`\"$(ConvertTo-JsonString $trusteeSam)`\",`\"TrusteeType`\":`\"$trusteeType`\",`\"TargetDN`\":`\"$(ConvertTo-JsonString $dn)`\",`\"Right`\":`\"$(ConvertTo-JsonString $right)`\",`\"RightCategory`\":`\"$rightCategory`\",`\"IsInherited`\":$isInherited,`\"Tier`\":`\"$(ConvertTo-JsonString $tierVal)`\"}\")");
            L(s, "            }");
            L(s, "            if ($delegParts.Count -gt 0) { $delegationsJson = '[' + ($delegParts -join ',') + ']' }");
            L(s, "        } catch {}");
            L(s, "    }");
            L(s, "");
            L(s, "    # PSO fields");
            L(s, "    $psoAppliesToJson = '[]'");
            L(s, "    $psoPrec = $psoMinLen = $psoHistory = $psoComplex = $psoMaxAge = $psoMinAge = $psoLockThr = $psoLockDur = $psoLockObs = 'null'");
            L(s, "    if ($simType -eq 'PasswordSettingsObject') {");
            L(s, "        $pso = $psoObjects | Where-Object { $_.DistinguishedName -eq $dn } | Select-Object -First 1");
            L(s, "        if ($pso) {");
            L(s, "            $psoPrec    = $pso.Precedence");
            L(s, "            $psoMinLen  = $pso.MinPasswordLength");
            L(s, "            $psoHistory = $pso.PasswordHistoryCount");
            L(s, "            $psoComplex = ($pso.ComplexityEnabled).ToString().ToLower()");
            L(s, "            $psoMaxAge  = if ($pso.MaxPasswordAge) { [int]$pso.MaxPasswordAge.TotalDays } else { 'null' }");
            L(s, "            $psoMinAge  = if ($pso.MinPasswordAge) { [int]$pso.MinPasswordAge.TotalDays } else { 'null' }");
            L(s, "            $psoLockThr = $pso.LockoutThreshold");
            L(s, "            $psoLockDur = if ($pso.LockoutDuration) { [int]$pso.LockoutDuration.TotalMinutes } else { 'null' }");
            L(s, "            $psoLockObs = if ($pso.LockoutObservationWindow) { [int]$pso.LockoutObservationWindow.TotalMinutes } else { 'null' }");
            L(s, "            $sams = foreach ($sdn in $pso.AppliesTo) {");
            L(s, "                try { $o = Get-ADObject -Identity $sdn -Properties SAMAccountName; $o.SAMAccountName } catch {}");
            L(s, "            }");
            L(s, "            $sams = @($sams | Where-Object { $_ })");
            L(s, "            if (@($sams).Count -gt 0) {");
            L(s, "                $psoAppliesToJson = '[' + (($sams | ForEach-Object { '\"' + (ConvertTo-JsonString $_) + '\"' }) -join ',') + ']'");
            L(s, "            }");
            L(s, "        }");
            L(s, "    }");
            L(s, "");
            L(s, "    # Children (OUs/Containers + leaves)");
            L(s, "    $childParts = [System.Collections.Generic.List[string]]::new()");
            L(s, "");
            L(s, "    try {");
            L(s, "        $subOUs = Get-ADObject -Filter { (objectClass -eq 'organizationalUnit') -or (objectClass -eq 'container') -or (objectClass -eq 'builtinDomain') } `");
            L(s, "                               -SearchBase $dn -SearchScope OneLevel `");
            L(s, "                               -Properties WhenCreated,WhenChanged,Description,gpLink |");
            L(s, "                     Where-Object { $_.ObjectClass -ne 'groupPolicyContainer' } |");
            L(s, "                     Where-Object { -not ($_.Name -eq 'Operations' -and $_.DistinguishedName -match 'CN=DomainUpdates') }");
            L(s, "        foreach ($c in $subOUs) {");
            L(s, "            $childParts.Add((Build-NodeJson -dn $c.DistinguishedName -name $c.Name -simType (Get-SimType $c.ObjectClass) -adObj $c -depth ($depth+1)))");
            L(s, "        }");
            L(s, "    } catch {}");
            L(s, "");
            L(s, "    try {");
            L(s, "        $leaves = Get-ADObject -Filter { (objectClass -eq 'user') -or (objectClass -eq 'group') -or (objectClass -eq 'computer') -or (objectClass -eq 'msDS-GroupManagedServiceAccount') -or (objectClass -eq 'groupPolicyContainer') -or (objectClass -eq 'msDS-PasswordSettings') } `");
            L(s, "                               -SearchBase $dn -SearchScope OneLevel `");
            L(s, "                               -Properties SAMAccountName,MemberOf,WhenCreated,WhenChanged,Description,ObjectClass,DisplayName");
            L(s, "        foreach ($l in $leaves) {");
            L(s, "            if ($l.ObjectClass -eq 'groupPolicyContainer') {");
            L(s, "                # Use DisplayName as node name; fallback to CN (GUID) if absent");
            L(s, "                $gpoDisplayName = if ($l.DisplayName) { $l.DisplayName } else { $l.Name }");
            L(s, "                $childParts.Add((Build-NodeJson -dn $l.DistinguishedName -name $gpoDisplayName -simType 'Policy' -adObj $l -depth ($depth+1)))");
            L(s, "            } else {");
            L(s, "                $childParts.Add((Build-NodeJson -dn $l.DistinguishedName -name $l.Name -simType (Get-SimType $l.ObjectClass) -adObj $l -depth ($depth+1)))");
            L(s, "            }");
            L(s, "        }");
            L(s, "    } catch {}");
            L(s, "");
            L(s, "    $childrenJson = if ($childParts.Count -gt 0) { '[' + ($childParts -join ',') + ']' } else { '[]' }");
            L(s, "");
            L(s, "    return \"{`\"Id`\":`\"$id`\",`\"Name`\":`\"$(ConvertTo-JsonString $name)`\",`\"Type`\":`\"$simType`\",`\"Description`\":`\"$description`\",`\"DistinguishedName`\":`\"$(ConvertTo-JsonString $dn)`\",`\"Children`\":$childrenJson,`\"MemberOf`\":$memberOfJson,`\"LinkedGPOs`\":$linkedGPOJson,`\"Delegations`\":$delegationsJson,`\"PSOAppliesTo`\":$psoAppliesToJson,`\"PSOPrecedence`\":$psoPrec,`\"PSOMinPasswordLength`\":$psoMinLen,`\"PSOPasswordHistoryCount`\":$psoHistory,`\"PSOComplexityEnabled`\":$psoComplex,`\"PSOMaxPasswordAgeDays`\":$psoMaxAge,`\"PSOMinPasswordAgeDays`\":$psoMinAge,`\"PSOLockoutThreshold`\":$psoLockThr,`\"PSOLockoutDurationMinutes`\":$psoLockDur,`\"PSOLockoutObservationWindowMinutes`\":$psoLockObs,`\"CreatedDate`\":`\"$created`\",`\"ModifiedDate`\":`\"$modified`\"}\"");
            L(s, "}");
            L(s, "");
            L(s, "# ── 9. Domain root ─────────────────────────────────────────────────────────");
            L(s, "Write-Host 'Building tree...' -ForegroundColor Yellow");
            L(s, "$domainAdObj = Get-ADDomain");
            L(s, "$rootJson    = Build-NodeJson -dn $DomainDN -name $domainName -simType 'Domain' -adObj $domainAdObj -depth 0");
            L(s, "");
            L(s, "# ── 10. Sites topology ──────────────────────────────────────────────────────");
            L(s, "Write-Host 'Collecting Sites topology...' -ForegroundColor Yellow");
            L(s, "$sitesJsonParts  = [System.Collections.Generic.List[string]]::new()");
            L(s, "$linksJsonParts  = [System.Collections.Generic.List[string]]::new()");
            L(s, "");
            L(s, "try {");
            L(s, "    $adSites = Get-ADReplicationSite -Filter * -Properties Name,Description,Location,WhenCreated,WhenChanged");
            L(s, "    foreach ($site in $adSites) {");
            L(s, "        $siteName    = ConvertTo-JsonString $site.Name");
            L(s, "        $siteDesc    = ConvertTo-JsonString $site.Description");
            L(s, "        $siteLoc     = ConvertTo-JsonString $site.Location");
            L(s, "        $siteCreated = Format-Date $site.WhenCreated");
            L(s, "        $siteMod     = Format-Date $site.WhenChanged");
            L(s, "        $siteTier    = ''");
            L(s, "");
            L(s, "        # Linked GPOs for this site (gpLink attribute on site object)");
            L(s, "        $siteLinkedGPOJson = '[]'");
            L(s, "        try {");
            L(s, "            $siteGPOLinks = @(Get-GPOLinksForDN $site.DistinguishedName)");
            L(s, "            if ($siteGPOLinks.Count -gt 0) {");
            L(s, "                $siteLinkedGPOJson = '[' + (($siteGPOLinks | ForEach-Object { '\"' + (ConvertTo-JsonString $_) + '\"' }) -join ',') + ']'");
            L(s, "            }");
            L(s, "        } catch {}");
            L(s, "");
            L(s, "        # Domain Controllers in this site");
            L(s, "        $dcParts = [System.Collections.Generic.List[string]]::new()");
            L(s, "        try {");
            L(s, "            Get-ADDomainController -Filter { Site -eq $site.Name } |");
            L(s, "                ForEach-Object { $dcParts.Add(\"`\"$(ConvertTo-JsonString $_.HostName)`\"\") }");
            L(s, "        } catch {}");
            L(s, "        $dcsJson = '[' + ($dcParts -join ',') + ']'");
            L(s, "");
            L(s, "        # Subnets assigned to this site");
            L(s, "        $subnetParts = [System.Collections.Generic.List[string]]::new()");
            L(s, "        try {");
            L(s, "            Get-ADReplicationSubnet -Filter { Site -eq $site.Name } -Properties Name,Description,Location |");
            L(s, "                ForEach-Object {");
            L(s, "                    $cidr    = ConvertTo-JsonString $_.Name");
            L(s, "                    $sDesc   = ConvertTo-JsonString $_.Description");
            L(s, "                    $sLoc    = ConvertTo-JsonString $_.Location");
            L(s, "                    $subnetParts.Add(\"{`\"Cidr`\":`\"$cidr`\",`\"SiteName`\":`\"$siteName`\",`\"Description`\":`\"$sDesc`\",`\"Location`\":`\"$sLoc`\"}\")");
            L(s, "                }");
            L(s, "        } catch {}");
            L(s, "        $subnetsJson = '[' + ($subnetParts -join ',') + ']'");
            L(s, "");
            L(s, "        $sitesJsonParts.Add(\"{`\"Id`\":`\"$(New-Guid)`\",`\"Name`\":`\"$siteName`\",`\"Description`\":`\"$siteDesc`\",`\"Location`\":`\"$siteLoc`\",`\"Subnets`\":$subnetsJson,`\"DomainControllers`\":$dcsJson,`\"LinkedGPOs`\":$siteLinkedGPOJson,`\"Tier`\":`\"$siteTier`\",`\"CreatedDate`\":`\"$siteCreated`\",`\"ModifiedDate`\":`\"$siteMod`\"}\")");
            L(s, "    }");
            L(s, "} catch {");
            L(s, "    Write-Warning \"Could not collect Sites: $_\"");
            L(s, "}");
            L(s, "");
            L(s, "try {");
            L(s, "    Get-ADReplicationSiteLink -Filter * -Properties Name,DistinguishedName,Cost,ReplicationFrequencyInMinutes,SitesIncluded,Description |");
            L(s, "        ForEach-Object {");
            L(s, "            $linkName      = ConvertTo-JsonString $_.Name");
            L(s, "            $linkDesc      = ConvertTo-JsonString $_.Description");
            L(s, "            $linkCost      = if ($_.Cost) { $_.Cost } else { 100 }");
            L(s, "            $linkInterval  = if ($_.ReplicationFrequencyInMinutes) { $_.ReplicationFrequencyInMinutes } else { 180 }");
            L(s, "            $linkTransport = if ($_.DistinguishedName -match 'CN=SMTP,CN=Inter-Site Transports') { 'SMTP' } else { 'IP' }");
            L(s, "            $siteNames     = ($_.SitesIncluded | ForEach-Object {");
            L(s, "                $sn = ($_ -split ',')[0] -replace '^CN=',''");
            L(s, "                \"`\"$(ConvertTo-JsonString $sn)`\"\"");
            L(s, "            }) -join ','");
            L(s, "            $linksJsonParts.Add(\"{`\"Name`\":`\"$linkName`\",`\"Transport`\":`\"$linkTransport`\",`\"SiteNames`\":[$siteNames],`\"Cost`\":$linkCost,`\"ReplicationIntervalMinutes`\":$linkInterval,`\"ReplicationSchedule`\":`\"Always`\",`\"BridgeheadAuto`\":true,`\"Description`\":`\"$linkDesc`\"}\")");
            L(s, "        }");
            L(s, "} catch {");
            L(s, "    Write-Warning \"Could not collect Site Links: $_\"");
            L(s, "}");
            L(s, "");
            L(s, "$sitesTopologyJson = \"{`\"Sites`\":[\" + ($sitesJsonParts -join ',') + \"],`\"SiteLinks`\":[\" + ($linksJsonParts -join ',') + \"]}\"");
            L(s, "");
            L(s, "# ── 11. Write output (v2 format) ─────────────────────────────────────────────");
            L(s, "$outDir = Split-Path $OutputPath -Parent");
            L(s, "if ($outDir -and -not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }");
            L(s, "");
            L(s, "# Wrap in v2 document { Version, Domain, SitesTopology }");
            L(s, "$v2Json = \"{`\"Version`\":2,`\"Domain`\":$rootJson,`\"SitesTopology`\":$sitesTopologyJson}\"");
            L(s, "$v2Json | Out-File -FilePath $OutputPath -Encoding UTF8 -Force");
            L(s, "");
            L(s, "Write-Host ''");
            L(s, "Write-Host '====================================' -ForegroundColor Green");
            L(s, "Write-Host ' Export completed successfully !'       -ForegroundColor Green");
            L(s, "Write-Host \" File : $OutputPath\"                -ForegroundColor Green");
            L(s, "Write-Host '====================================' -ForegroundColor Green");
            L(s, "Write-Host ' Import this file into SMAD-X' -ForegroundColor Cyan");
            L(s, "Write-Host ' via : File > Open'                -ForegroundColor Cyan");
            return s.ToString();
        }

        private static void L(StringBuilder sb, string line) => sb.AppendLine(line);
    }
}
